apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: fms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: {{ .Values.django.image }}
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: django-env
