apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: fms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: {{ .Values.fastapi.image }}
        ports:
        - containerPort: 8001
        envFrom:
        - configMapRef:
            name: fastapi-env
