version: '3'
services:
  web:
    build: .
    container_name: fms
    image: fms
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
  